import type { Email, User, AnalyticsData, AutomationRule, SavedPassword, WebhookConfig } from "@/types/email";

export const MOCK_USER: User = {
  id: "usr_01",
  name: "Alex Chen",
  email: "alex.chen@iqmail.io",
  avatar: "https://i.pravatar.cc/150?img=12",
  role: "Product Lead",
  plan: "pro",
  storageUsed: 4.2,
  storageTotal: 15,
  unreadCount: 12,
};

export const MOCK_EMAILS: Email[] = [
  {
    id: "em_001",
    from: "Sarah Johnson",
    fromEmail: "sarah.j@techcorp.io",
    fromAvatar: "https://i.pravatar.cc/40?img=5",
    to: ["alex.chen@iqmail.io"],
    subject: "Q4 Product Roadmap Review — Action Required",
    preview: "Hi Alex, I've just uploaded the Q4 roadmap to Notion. Could you review and leave comments before...",
    body: `<p>Hi Alex,</p><p>I've just uploaded the Q4 roadmap to Notion. Could you review and leave comments before our sync on Thursday? There are a few key decisions we need to align on regarding the new AI features and the timeline for the mobile launch.</p><p>Key items to review:</p><ul><li>Feature prioritization for Nov–Dec sprint</li><li>Resource allocation between mobile and API teams</li><li>Customer feedback integration plan</li></ul><p>Looking forward to your thoughts!</p><p>Best,<br/>Sarah</p>`,
    timestamp: "2026-09-18T09:30:00Z",
    isRead: false,
    isStarred: true,
    isImportant: true,
    folder: "inbox",
    labels: ["Work", "Action Required"],
    priority: "high",
    hasAttachments: false,
    aiSummary: "Q4 roadmap uploaded to Notion. Review needed before Thursday sync. Focus on AI features, mobile launch timeline.",
  },
  {
    id: "em_002",
    from: "GitHub",
    fromEmail: "noreply@github.com",
    fromAvatar: "https://github.com/favicon.ico",
    to: ["alex.chen@iqmail.io"],
    subject: "[iqmail/core] PR #247: Add AI email summarization",
    preview: "Pull request #247 opened by @dev-marcus: Implements GPT-based email summarization with streaming...",
    body: `<p><strong>Pull Request #247</strong></p><p>@dev-marcus opened a pull request: <strong>Add AI email summarization with streaming responses</strong></p><p>This PR implements the email summarization feature using the OpenAI API with streaming support. Key changes:</p><ul><li>New <code>EmailSummarizer</code> service with retry logic</li><li>Streaming response handling in the UI</li><li>Rate limiting and cost controls</li></ul><p><a href="#">Review Pull Request</a></p>`,
    timestamp: "2026-09-18T08:15:00Z",
    isRead: false,
    isStarred: false,
    isImportant: false,
    folder: "inbox",
    labels: ["GitHub", "Dev"],
    priority: "medium",
    hasAttachments: false,
    aiSummary: "New PR #247 for AI email summarization with GPT streaming. Includes rate limiting and cost controls.",
  },
  {
    id: "em_003",
    from: "Cloudflare",
    fromEmail: "billing@cloudflare.com",
    fromAvatar: "https://www.cloudflare.com/favicon.ico",
    to: ["alex.chen@iqmail.io"],
    subject: "Your Cloudflare invoice for September 2026",
    preview: "Invoice #CF-2026-09-4821 | Amount Due: $142.00 | Due Date: October 1, 2026...",
    body: `<p>Your Cloudflare Invoice for September 2026</p><p><strong>Invoice #CF-2026-09-4821</strong></p><table><tr><td>Workers (Pro)</td><td>$25.00</td></tr><tr><td>R2 Storage (42 GB)</td><td>$63.00</td></tr><tr><td>Email Routing</td><td>$0.00</td></tr><tr><td>DDoS Protection</td><td>$54.00</td></tr><tr><td><strong>Total</strong></td><td><strong>$142.00</strong></td></tr></table><p>Due: October 1, 2026</p>`,
    timestamp: "2026-09-17T16:00:00Z",
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "inbox",
    labels: ["Billing", "Cloudflare"],
    priority: "medium",
    hasAttachments: true,
    attachments: [{ id: "att_1", name: "CF-invoice-sep2026.pdf", size: "248 KB", type: "pdf" }],
    aiSummary: "Cloudflare invoice $142 due Oct 1. Workers $25, R2 Storage $63, DDoS $54.",
  },
  {
    id: "em_004",
    from: "Resend",
    fromEmail: "support@resend.com",
    fromAvatar: "https://resend.com/favicon.ico",
    to: ["alex.chen@iqmail.io"],
    subject: "Your API key has been created successfully",
    preview: "Your new Resend API key re_live_abc123... has been created. Store it securely as it won't be shown again...",
    body: `<p>Hi Alex,</p><p>Your new Resend API key has been created successfully.</p><p><strong>Key ID:</strong> re_live_abc123xyz789</p><p>Important: This key will not be shown again. Make sure to store it in a secure location.</p><p>You can manage your API keys from the <a href="#">Resend Dashboard</a>.</p><p>— The Resend Team</p>`,
    timestamp: "2026-09-17T11:20:00Z",
    isRead: true,
    isStarred: true,
    isImportant: true,
    folder: "inbox",
    labels: ["API", "Resend"],
    priority: "high",
    hasAttachments: false,
    aiSummary: "New Resend API key created. Store securely - won't be shown again.",
  },
  {
    id: "em_005",
    from: "Marcus Webb",
    fromEmail: "marcus.w@iqmail.io",
    fromAvatar: "https://i.pravatar.cc/40?img=8",
    to: ["alex.chen@iqmail.io"],
    subject: "Design handoff for mobile nav — files attached",
    preview: "Hey! The mobile navigation designs are ready in Figma. I've exported the specs and assets...",
    body: `<p>Hey Alex!</p><p>The mobile navigation designs are ready in Figma. I've exported all specs and assets. The main changes from last iteration:</p><ul><li>Bottom tab bar with haptic feedback zones</li><li>Swipe gestures for inbox switching</li><li>New compose FAB animation</li></ul><p>Let me know if you need any adjustments. I'm available for a walkthrough tomorrow.</p><p>Marcus</p>`,
    timestamp: "2026-09-16T14:45:00Z",
    isRead: false,
    isStarred: false,
    isImportant: false,
    folder: "inbox",
    labels: ["Design", "Team"],
    priority: "low",
    hasAttachments: true,
    attachments: [
      { id: "att_2", name: "mobile-nav-specs.fig", size: "4.2 MB", type: "figma" },
      { id: "att_3", name: "nav-assets.zip", size: "1.8 MB", type: "zip" },
    ],
  },
  {
    id: "em_006",
    from: "Stripe",
    fromEmail: "receipts@stripe.com",
    fromAvatar: "https://stripe.com/favicon.ico",
    to: ["alex.chen@iqmail.io"],
    subject: "Payment confirmation: IQMAIL Pro Plan",
    preview: "Your payment of $49.00 for IQMAIL Pro Plan has been confirmed. Transaction ID: txn_3P...",
    body: `<p>Payment Confirmed</p><p>Amount: <strong>$49.00</strong></p><p>Plan: IQMAIL Pro (Monthly)</p><p>Transaction ID: txn_3PqR8KLwE...</p><p>Next billing date: October 18, 2026</p>`,
    timestamp: "2026-09-15T09:00:00Z",
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "inbox",
    labels: ["Billing"],
    priority: "low",
    hasAttachments: true,
    attachments: [{ id: "att_4", name: "receipt-sep2026.pdf", size: "124 KB", type: "pdf" }],
  },
  {
    id: "em_007",
    from: "Alex Chen",
    fromEmail: "alex.chen@iqmail.io",
    fromAvatar: "https://i.pravatar.cc/40?img=12",
    to: ["team@iqmail.io"],
    subject: "Weekly team update — Sprint 23 recap",
    preview: "Team, here's the weekly update for Sprint 23. We shipped 3 major features and closed 14 bugs...",
    body: `<p>Team,</p><p>Here's the Sprint 23 weekly update:</p><p><strong>Shipped:</strong></p><ul><li>AI email summarization (beta)</li><li>Webhook management UI</li><li>Dark mode improvements</li></ul><p><strong>In Progress:</strong></p><ul><li>Email thread view</li><li>Analytics v2 dashboard</li></ul><p><strong>Next Sprint Goals:</strong></p><ul><li>Mobile app beta</li><li>SMTP relay integration</li></ul>`,
    timestamp: "2026-09-14T17:00:00Z",
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "sent",
    labels: ["Team"],
    priority: "medium",
    hasAttachments: false,
  },
  {
    id: "em_008",
    from: "LinkedIn",
    fromEmail: "jobs@linkedin.com",
    fromAvatar: "https://static.licdn.com/sc/h/al2o9zrvru7aqj8e1x2rzsrca",
    to: ["alex.chen@iqmail.io"],
    subject: "You appeared in 47 searches this week",
    preview: "Your LinkedIn profile appeared in 47 searches in the last 7 days. Recruiters from Google, Apple...",
    body: `<p>Hi Alex,</p><p>Your profile is getting noticed! You appeared in <strong>47 searches</strong> this week.</p><p>Top companies viewing your profile: Google, Apple, Stripe, Notion</p>`,
    timestamp: "2026-09-14T08:00:00Z",
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "inbox",
    labels: ["Social"],
    priority: "low",
    hasAttachments: false,
  },
  {
    id: "em_009",
    from: "DataDog",
    fromEmail: "alerts@datadoghq.com",
    fromAvatar: "https://imgix.datadoghq.com/img/dd_logo_n_70x75.png",
    to: ["alex.chen@iqmail.io"],
    subject: "🔴 Alert: API latency spike detected",
    preview: "CRITICAL: API endpoint /v1/emails/send latency exceeded 2000ms threshold. P95: 2,847ms...",
    body: `<p>🔴 <strong>Critical Alert</strong></p><p>Monitor: API Latency - Production</p><p>Status: ALERT</p><p>P95 Latency: 2,847ms (threshold: 2000ms)</p><p>Affected endpoint: POST /v1/emails/send</p><p>Started: 2026-09-13 22:14 UTC</p>`,
    timestamp: "2026-09-13T22:14:00Z",
    isRead: true,
    isStarred: false,
    isImportant: true,
    folder: "inbox",
    labels: ["Alerts", "Ops"],
    priority: "high",
    hasAttachments: false,
    aiSummary: "Critical API latency alert on /v1/emails/send. P95 at 2847ms, threshold exceeded.",
  },
  {
    id: "em_010",
    from: "Newsletter: Product Hunt",
    fromEmail: "digest@producthunt.com",
    fromAvatar: "https://ph-files.imgix.net/favicon.ico",
    to: ["alex.chen@iqmail.io"],
    subject: "Today's top products: AI tools dominate September",
    preview: "Today's featured products include 3 AI email tools, a new design system, and a startup...",
    body: `<p>Product Hunt Daily Digest</p><p>Today's top products are dominated by AI tools...</p>`,
    timestamp: "2026-09-13T12:00:00Z",
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: "inbox",
    labels: ["Newsletter"],
    priority: "low",
    hasAttachments: false,
  },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  emailsReceived: 847,
  emailsSent: 312,
  emailsRead: 798,
  responseRate: 87,
  avgResponseTime: "1h 23m",
  topSenders: [
    { name: "Sarah Johnson", email: "sarah.j@techcorp.io", count: 48, avatar: "https://i.pravatar.cc/40?img=5" },
    { name: "Marcus Webb", email: "marcus.w@iqmail.io", count: 37, avatar: "https://i.pravatar.cc/40?img=8" },
    { name: "GitHub", email: "noreply@github.com", count: 124, avatar: "https://i.pravatar.cc/40?img=14" },
    { name: "Cloudflare", email: "billing@cloudflare.com", count: 12, avatar: "https://i.pravatar.cc/40?img=3" },
    { name: "DataDog", email: "alerts@datadoghq.com", count: 89, avatar: "https://i.pravatar.cc/40?img=7" },
  ],
  dailyActivity: [
    { hour: "6am", received: 4, sent: 1 },
    { hour: "7am", received: 12, sent: 3 },
    { hour: "8am", received: 28, sent: 8 },
    { hour: "9am", received: 45, sent: 22 },
    { hour: "10am", received: 52, sent: 31 },
    { hour: "11am", received: 38, sent: 28 },
    { hour: "12pm", received: 15, sent: 7 },
    { hour: "1pm", received: 22, sent: 14 },
    { hour: "2pm", received: 41, sent: 25 },
    { hour: "3pm", received: 47, sent: 33 },
    { hour: "4pm", received: 35, sent: 19 },
    { hour: "5pm", received: 18, sent: 12 },
    { hour: "6pm", received: 8, sent: 4 },
  ],
  categoryBreakdown: [
    { name: "Work", value: 38, color: "#00D4FF" },
    { name: "Newsletters", value: 22, color: "#8B5CF6" },
    { name: "Billing", value: 12, color: "#F59E0B" },
    { name: "Social", value: 18, color: "#10B981" },
    { name: "Alerts", value: 10, color: "#EF4444" },
  ],
  weeklyTrend: [
    { day: "Mon", received: 124, sent: 45, read: 118 },
    { day: "Tue", received: 89, sent: 67, read: 82 },
    { day: "Wed", received: 145, sent: 89, read: 138 },
    { day: "Thu", received: 97, sent: 52, read: 90 },
    { day: "Fri", received: 167, sent: 44, read: 155 },
    { day: "Sat", received: 45, sent: 12, read: 43 },
    { day: "Sun", received: 38, sent: 8, read: 35 },
  ],
};

export const MOCK_AUTOMATIONS: AutomationRule[] = [
  {
    id: "auto_1",
    name: "Auto-label GitHub notifications",
    trigger: "From: github.com",
    action: "Apply label: Dev, Move to: Dev folder",
    isActive: true,
    runCount: 847,
    lastRun: "2 min ago",
  },
  {
    id: "auto_2",
    name: "Priority alerts to important",
    trigger: "Subject contains: CRITICAL or 🔴",
    action: "Mark as Important, Star email",
    isActive: true,
    runCount: 23,
    lastRun: "1 hour ago",
  },
  {
    id: "auto_3",
    name: "Newsletter digest",
    trigger: "Label: Newsletter",
    action: "Archive after 7 days if unread",
    isActive: true,
    runCount: 412,
    lastRun: "6 hours ago",
  },
  {
    id: "auto_4",
    name: "Invoice archiver",
    trigger: "From: billing@, receipts@",
    action: "Apply label: Billing, Archive copy to Drive",
    isActive: false,
    runCount: 67,
    lastRun: "2 days ago",
  },
  {
    id: "auto_5",
    name: "Daily summary webhook",
    trigger: "Schedule: 9:00 AM daily",
    action: "POST summary to Slack webhook",
    isActive: true,
    runCount: 89,
    lastRun: "9 hours ago",
  },
];

export const MOCK_PASSWORDS: SavedPassword[] = [
  { id: "pw_1", site: "Cloudflare Dashboard", username: "alex.chen@iqmail.io", password: "••••••••••••", lastUsed: "Today", strength: "strong", icon: "https://www.cloudflare.com/favicon.ico" },
  { id: "pw_2", site: "GitHub", username: "alexchen-dev", password: "••••••••••••", lastUsed: "2 hours ago", strength: "strong", icon: "https://github.com/favicon.ico" },
  { id: "pw_3", site: "Resend Console", username: "alex.chen@iqmail.io", password: "••••••••", lastUsed: "Yesterday", strength: "medium", icon: "https://resend.com/favicon.ico" },
  { id: "pw_4", site: "Stripe Dashboard", username: "alex@iqmail.io", password: "••••••••••", lastUsed: "3 days ago", strength: "strong", icon: "https://stripe.com/favicon.ico" },
  { id: "pw_5", site: "DataDog", username: "alex.chen@iqmail.io", password: "••••••", lastUsed: "1 week ago", strength: "weak", icon: "https://i.pravatar.cc/20?img=5" },
];

export const MOCK_WEBHOOKS: WebhookConfig[] = [
  {
    id: "wh_1",
    name: "Slack Notifications",
    url: "https://hooks.slack.com/services/T0.../B0.../xxx",
    events: ["email.received", "email.important", "alert.triggered"],
    isActive: true,
    lastTriggered: "5 min ago",
    successCount: 1247,
    failureCount: 3,
  },
  {
    id: "wh_2",
    name: "CRM Sync (HubSpot)",
    url: "https://api.hubspot.com/webhooks/v1/...",
    events: ["email.sent", "contact.new"],
    isActive: true,
    lastTriggered: "1 hour ago",
    successCount: 389,
    failureCount: 7,
  },
  {
    id: "wh_3",
    name: "Zapier Automation",
    url: "https://hooks.zapier.com/hooks/catch/...",
    events: ["email.received", "email.label_added"],
    isActive: false,
    lastTriggered: "3 days ago",
    successCount: 56,
    failureCount: 1,
  },
];

export const FOLDER_COUNTS = {
  inbox: 12,
  sent: 0,
  drafts: 3,
  starred: 4,
  spam: 2,
  trash: 0,
  archive: 0,
};
